import tkinter
from tkinter import *
root = tkinter.Tk()
root.geometry("1000x1000")
root.title("Personal Translator")
def convert():
    inputText=text1.get("1.0", "end")
    print(inputText)
    text2.insert("end", inputText)
text1=Text(root, height=5, width=30,bg='#6A5ACD')
text1.grid(row=1,column=1)
text2=Text(root, height=5, width=30, bg='#F0E68C')
text2.grid(row=2, column=1)
button1=Button(root, text='japan', bg='#4B0082',font='amarantha 12', fg='cyan', padx='50', pady='10', command = convert)
button1.grid(row=1, column=11)
button2=Button(root, text='china', bg='#4B0082',font='amarantha 12', fg='cyan', padx='50', pady='10',)
button2.grid(row=1, column=9)
button3=Button(root, text='India', bg='#4B0082',font='amarantha 12', fg='cyan', padx='50', pady='10')
button3.grid(row=1, column=7)
button4=Button(root, text='france', bg='#4B0082',font='amarantha 12', fg='cyan', padx='50', pady='10')
button4.grid(row=1, column=5)
button5=Button(root, text='canada', bg='#4B0082',font='amarantha 12', fg='cyan', padx='50', pady='10')
button5.grid(row=1, column=3)
root.mainloop()
