import tkinter
from tkinter import *
from google_trans_new import google_translator
translator = google_translator()
root =Tk()
root.geometry("2000x2000")
root.title("Personal Translator")
root.configure(bg="#b8b894")
button101=Button(root, text='TRANSLATE', bg='#5F9EA0',font='Papyrus 14', fg='#003366', padx='50', pady='10')
button101.place(x=550, y=200)
def convert():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='ja')
    text2.insert("end", out)
def convert1():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='bg')
    text2.insert("end", out)
def convert2():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='it')
    text2.insert("end", out)
def convert3():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='fr')
    text2.insert("end", out)
def convert4():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='bn')
    text2.insert("end", out)
def convert5():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='es')
    text2.insert("end", out)
def convert6():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='da')
    text2.insert("end", out)
def convert7():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='no')
    text2.insert("end", out)
def convert8():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='ur')
    text2.insert("end", out)
def convert9():
    inputText=text1.get("1.0", "end")
    print(inputText)
    out = translator.translate(inputText, lang_tgt='vi')
    text2.insert("end", out)
text1=Text(root, height=5, width=30,bg='#6A5ACD')
text1.grid(row=1,column=1)
text2=Text(root, height=5, width=30, bg='#F0E68C')
text2.grid(row=2, column=1)
button1=Button(root, text='JAPANESE', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command = convert)
button1.grid(row=1, column=11)
button2=Button(root, text='BULGARIAN', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command= convert1 )
button2.grid(row=1, column=9)
button3=Button(root, text='ITALIAN', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command= convert2)
button3.grid(row=1, column=7)
button4=Button(root, text='FRENCH', bg='#4d1a00',font='Garamond', fg='#ffffcc', padx='50', pady='10', command=convert3)
button4.grid(row=1, column=5)
button5=Button(root, text='BANGLA', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert4)
button5.grid(row=1, column=3)
button6=Button(root, text='SPANISH', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert5)
button6.grid(row=2, column=3)
button6=Button(root, text='DANISH', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert6)
button6.grid(row=2, column=5)
button7=Button(root, text='Norwegian', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert7)
button7.grid(row=2, column=7)
button8=Button(root, text='URDU', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert8)
button8.grid(row=2, column=9)
button9=Button(root, text='VIETNAMESE', bg='#4d1a00',font='Garamond 12', fg='#ffffcc', padx='50', pady='10', command=convert9)
button9.grid(row=2, column=11)
def clear():
    text1.delete(1.0, END)
    text2.delete(1.0,END)
button10 = Button(root, text='clear', bg='#00ffbf',fg='black',command=clear)
button10.grid(row=4,column=1, padx=10, pady=10)
buttonExit = Button(root, text='close', bg='#00ffbf',fg='black', command=root.destroy)
buttonExit.grid(row=5, column=1, padx=10, pady=10)
root.mainloop()